export const installments = [
    { times: 2 },
    { times: 3 },
    { times: 4 },
    { times: 5 },
    { times: 6 },
    { times: 7 },
    { times: 8 },
    { times: 9 },
    { times: 10 },
    { times: 11 },
    { times: 12 },
    { times: 13 },
    { times: 14 },
    { times: 15 },
    { times: 16 },
    { times: 17 },
    { times: 18 },
    { times: 19 },
    { times: 20 },
    { times: 21 },
    { times: 22 },
    { times: 23 },
    { times: 24 },
]